In [1]:
import pandas as pd
import sys
import getopt

args = sys.argv[1:]
opts, args = getopt.getopt(args, "r:g:b:h")

# Basic parameters

r_opt = [20]
g_opt = [6]
b_opt = [6]

for opt, arg in opts:
    if opt == "-r":
        x=int(arg)
        r_opt = [x]    
    elif opt == "-g":
        y=int(arg)
        g_opt == [y]
    elif opt == "-b":
        z=int(arg)
        b_opt = [z]
    elif opt == "-h":
        print("-r : Red bus line weight")
        print("-b : Blue bus line weight")
        print("-g : Green bus line weight")


#data open using pandas type Dataframe
df_standard = pd.read_csv ('fd_basic_F.csv', encoding = 'cp949')
df_to_add = pd.read_csv ('fd_2018_F.csv', encoding = 'cp949')

#extract_index_code_from_standard_data
index_code_standard=df_standard.drop_duplicates(['code'],keep='first')
index_list = index_code_standard.code.tolist()

def test_fu_only(code, standard_data, new_data):
    
    #Extract key value from df_to_add
    df_to_add_key = new_data[['y2017','y2018']]

    #df_to_add_listing
    to_add_list =[]
    for i in range(len(new_data)):
        data_2017 = df_to_add_key.iloc[i,0]
        data_2018 = df_to_add_key.iloc[i,1]
        to_add_list.append([data_2017,data_2018])

    #df_standard_listing
    standard_list = []
    for i in range(len(standard_data)):
        index_data_2017 = standard_data.iloc[i,6]
        standard_list.append(index_data_2017)

    #merge data
    for i in range(len(standard_list)):
        for j in range(len(to_add_list)):
            index_data = standard_list[i]
            if index_data == '0' :  standard_list[i] = [index_data,0]
            elif index_data == to_add_list[j][0] : standard_list[i] = [index_data, to_add_list[j][1]]

    #non data make 0    
    for i in range(len(standard_list)):
        non_data = standard_list[i]
        if type(standard_list[i]) != list : standard_list[i] = [non_data,0]

    #make index column
    for i in range(len(standard_list)):
        standard_list[i].insert(0,standard_data.iloc[i,0])
    
    #last_two_index_value
    standard_list[-1][2] = standard_data.iloc[-1,7]
    standard_list[-2][2] = standard_data.iloc[-2,7]
     
    return standard_list

test_dummys=[]
for i in range(len(index_list)):
    temp_standard =df_standard[df_standard['code']==index_list[i]]
    temp_new =df_to_add[df_to_add['code']==index_list[i]]
    test_data = test_fu_only(index_list,temp_standard,temp_new)
    test_dummys.append(test_data)

#df_origin_test=df_standard[df_standard['code'].isin([20,30,40])]

indexs=[] 
y2017s=[]
y2018s=[]
for test in test_dummys:
    for t in test:      
        index = t[0]
        y2017 = t[1]
        y2018 = t[2]
        indexs.append(index)
        y2017s.append(y2017)
        y2018s.append(y2018)
df_merge = pd.DataFrame({'Unnamed: 0':indexs,'y2018':y2018s})
merged_inner = pd.merge(left=df_standard, right=df_merge, left_on='Unnamed: 0', right_on='Unnamed: 0')

del merged_inner['y2018_x']
merged_inner.columns = ['Unnamed: 0','code','code_a','company','item','item_name','y2017','y2018']
#merged_inner.to_excel("Hi.xlsx")
#merged_inner

,Unnamed: 0,code,code_a,company,item,item_name,y2017,y2018
0,0,20,A000020,동화약품,6000901001,총자산(천원),"367,225,133","370,599,000,000"
1,1,20,A000020,동화약품,6000901101,총자산(평균)(천원),"345,914,835",0
2,2,20,A000020,동화약품,6000901002,유동자산(천원),"234,500,029","227,887,000,000"
3,3,20,A000020,동화약품,6000901005,당좌자산(천원),"197,893,786",0
4,4,20,A000020,동화약품,6000901030,현금및현금성자산(천원),"31,588,170","40,614,514,850"
5,5,20,A000020,동화약품,6000901010,단기금융자산(천원),"98,093,262",0
6,6,20,A000020,동화약품,6000901034,단기금융상품(천원),"95,020,000",0
7,7,20,A000020,동화약품,6000901009,단기유가증권(천원),"3,003,262",0
8,8,20,A000020,동화약품,6000901033,단기대여금(천원),"70,000",0
9,9,20,A000020,동화약품,6000901031,매출채권및기타채권(천원),"66,793,782",0
10,10,20,A000020,동화약품,6000901006,매출채권(천원),"61,630,747",0
11,11,20,A000020,동화약품,6000991002,단기미청구공사(천원),0,0
12,12,20,A000020,동화약품,6000901012,재고자산(천원),"36,606,243","43,717,602,702"
13,13,20,A000020,동화약품,6000991005,당기법인세자산(천원),0,0
14,14,20,A000020,동화약품,6000991006,매각예정비유동자산(천원),0,0
15,15,20,A000020,동화약품,6000901013,비유동자산(천원),"132,725,103","142,712,000,000"
16,16,20,A000020,동화약품,6000901014,장기금융자산(천원),"12,347,936",0
17,17,20,A000020,동화약품,6000901037,장기금융상품(천원),"2,012,000",0
18,18,20,A000020,동화약품,6000901054,매도가능금융자산(천원),"9,219,019","13,740,748,230"
19,19,20,A000020,동화약품,6000991007,만기보유금융자산(천원),0,0
20,20,20,A000020,동화약품,6000901040,장기대여금(천원),0,0
21,21,20,A000020,동화약품,6000991010,투자부동산(천원),0,0
22,22,20,A000020,동화약품,6000901015,관계기업등지분관련투자자산(천원),"9,609,969","9,886,571,567"
23,23,20,A000020,동화약품,6000901036,종속기업투자(천원),0,0
24,24,20,A000020,동화약품,6000991011,관계기업투자등(천원),"9,609,969","9,886,571,567"
25,25,20,A000020,동화약품,6000901017,유형자산(천원),"103,746,340","96,772,494,841"
26,26,20,A000020,동화약품,6000901041,토지(천원),"29,366,774",0
27,27,20,A000020,동화약품,6000991012,설비자산(천원),"73,187,024",0
28,28,20,A000020,동화약품,6000991013,기타유형자산(천원),"184,293",0
29,29,20,A000020,동화약품,6000901042,건설중인자산(천원),"1,008,250",0
...,...,...,...,...,...,...,...,...
890701,890701,950170,A950170,JTC,6000312004,"ROA(영업이익,3년평균)(%)",0,0
890702,890702,950170,A950170,JTC,6000306012,"ROA(영업이익,직전4분기)(%)",0,0
890703,890703,950170,A950170,JTC,6000306002,ROA(세전계속사업이익)(%),0,0
890704,890704,950170,A950170,JTC,6000306003,ROA(당기순이익)(%),0,0
890705,890705,950170,A950170,JTC,6000306015,"ROA(당기순이익,3년평균)(%)",0,0
890706,890706,950170,A950170,JTC,6000306005,ROA(총포괄이익)(%),0,0
890707,890707,950170,A950170,JTC,6000307001,ROE(영업이익)(%),0,0
890708,890708,950170,A950170,JTC,6000312005,"ROE(영업이익,3년평균)(%)",0,0
890709,890709,950170,A950170,JTC,6000307006,"ROE(영업이익,직전4분기)(%)",0,0
890710,890710,950170,A950170,JTC,6000307002,ROE(세전계속사업이익)(%),0,0
890711,890711,950170,A950170,JTC,6000312001,ROE(당기순이익)(%),0,0
890712,890712,950170,A950170,JTC,6000307015,"ROE(당기순이익,3년평균)(%)",0,0
890713,890713,950170,A950170,JTC,6000312002,"ROE(당기순이익,직전4분기)(%)",0,0
890714,890714,950170,A950170,JTC,6000307003,ROE(지배주주순이익)(%),0,0
890715,890715,950170,A950170,JTC,6000312006,"ROE(지배주주순이익,3년평균)(%)",0,0
890716,890716,950170,A950170,JTC,6000307005,"ROE(지배주주순이익,직전4분기)(%)",0,0
890717,890717,950170,A950170,JTC,6000307013,"ROE(지배주주순이익,기말)(%)",0,0
890718,890718,950170,A950170,JTC,6000307009,자본금영업이익률(%),0,0
890719,890719,950170,A950170,JTC,6000307010,자본금세전계속사업이익률(%),0,0
890720,890720,950170,A950170,JTC,6000307011,자본금지배주주순이익률(%),0,0
890721,890721,950170,A950170,JTC,6000401001,총자산회전율(회),0,0
890722,890722,950170,A950170,JTC,6000401006,총자산회전율(3년평균)(회),0,0
890723,890723,950170,A950170,JTC,6000402001,총부채회전율(회),0,0
890724,890724,950170,A950170,JTC,6000403001,총자본회전율(회),0,0
890725,890725,950170,A950170,JTC,6000403002,자본금회전율(회),0,0
890726,890726,950170,A950170,JTC,6000501001,부가가치(천원),0,0
890727,890727,950170,A950170,JTC,6000502001,자본생산성(%),0,0
890728,890728,950170,A950170,JTC,6000503001,노동생산성(천원),0,0
890729,890729,950170,A950170,JTC,S430000200,종가 (보통)(원),0,"17,900"
890730,890730,950170,A950170,JTC,S430002205,수정평균발행주식수 (보통+우선)(주),"25,077,000","34,216,676"